sudo: required
language: generic
services: docker

script:
  - bash .gen-tectonic.sh
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh tectonic-command 
